package main

var Teams = map[string]Team{
	"Jaguars":    {Wins: 0, Losses: 0, Ties: 0},
	"Ravens":     {Wins: 0, Losses: 0, Ties: 0},
	"Chiefs":     {Wins: 0, Losses: 0, Ties: 0},
	"Packers":    {Wins: 0, Losses: 0, Ties: 0},
	"Eagles":     {Wins: 0, Losses: 0, Ties: 0},
	"Steelers":   {Wins: 0, Losses: 0, Ties: 0},
	"Falcons":    {Wins: 0, Losses: 0, Ties: 0},
	"Cardinals":  {Wins: 0, Losses: 0, Ties: 0},
	"Bills":      {Wins: 0, Losses: 0, Ties: 0},
	"Titans":     {Wins: 0, Losses: 0, Ties: 0},
	"Bears":      {Wins: 0, Losses: 0, Ties: 0},
	"Patriots":   {Wins: 0, Losses: 0, Ties: 0},
	"Bengals":    {Wins: 0, Losses: 0, Ties: 0},
	"Texans":     {Wins: 0, Losses: 0, Ties: 0},
	"Colts":      {Wins: 0, Losses: 0, Ties: 0},
	"Dolphins":   {Wins: 0, Losses: 0, Ties: 0},
	"Panthers":   {Wins: 0, Losses: 0, Ties: 0},
	"Saints":     {Wins: 0, Losses: 0, Ties: 0},
	"Vikings":    {Wins: 0, Losses: 0, Ties: 0},
	"Giants":     {Wins: 0, Losses: 0, Ties: 0},
	"Raiders":    {Wins: 0, Losses: 0, Ties: 0},
	"Chargers":   {Wins: 0, Losses: 0, Ties: 0},
	"Broncos":    {Wins: 0, Losses: 0, Ties: 0},
	"Seahawks":   {Wins: 0, Losses: 0, Ties: 0},
	"Cowboys":    {Wins: 0, Losses: 0, Ties: 0},
	"Browns":     {Wins: 0, Losses: 0, Ties: 0},
	"Commanders": {Wins: 0, Losses: 0, Ties: 0},
	"Buccaneers": {Wins: 0, Losses: 0, Ties: 0},
	"Rams":       {Wins: 0, Losses: 0, Ties: 0},
	"Lions":      {Wins: 0, Losses: 0, Ties: 0},
	"Jets":       {Wins: 0, Losses: 0, Ties: 0},
	"49ers":      {Wins: 0, Losses: 0, Ties: 0},
}
