package main

var Teams = map[string]Team{
	"Jaguars":    {Name: "Jaguars", Wins: 0, Losses: 0, Ties: 0},
	"Ravens":     {Name: "Ravens", Wins: 0, Losses: 0, Ties: 0},
	"Chiefs":     {Name: "Chiefs", Wins: 0, Losses: 0, Ties: 0},
	"Packers":    {Name: "Packers", Wins: 0, Losses: 0, Ties: 0},
	"Eagles":     {Name: "Eagles", Wins: 0, Losses: 0, Ties: 0},
	"Steelers":   {Name: "Steelers", Wins: 0, Losses: 0, Ties: 0},
	"Falcons":    {Name: "Falcons", Wins: 0, Losses: 0, Ties: 0},
	"Cardinals":  {Name: "Cardinals", Wins: 0, Losses: 0, Ties: 0},
	"Bills":      {Name: "Bills", Wins: 0, Losses: 0, Ties: 0},
	"Titans":     {Name: "Titans", Wins: 0, Losses: 0, Ties: 0},
	"Bears":      {Name: "Bears", Wins: 0, Losses: 0, Ties: 0},
	"Patriots":   {Name: "Patriots", Wins: 0, Losses: 0, Ties: 0},
	"Bengals":    {Name: "Bengals", Wins: 0, Losses: 0, Ties: 0},
	"Texans":     {Name: "Texans", Wins: 0, Losses: 0, Ties: 0},
	"Colts":      {Name: "Colts", Wins: 0, Losses: 0, Ties: 0},
	"Dolphins":   {Name: "Dolphins", Wins: 0, Losses: 0, Ties: 0},
	"Panthers":   {Name: "Panthers", Wins: 0, Losses: 0, Ties: 0},
	"Saints":     {Name: "Saints", Wins: 0, Losses: 0, Ties: 0},
	"Vikings":    {Name: "Vikings", Wins: 0, Losses: 0, Ties: 0},
	"Giants":     {Name: "Giants", Wins: 0, Losses: 0, Ties: 0},
	"Raiders":    {Name: "Raiders", Wins: 0, Losses: 0, Ties: 0},
	"Chargers":   {Name: "Chargers", Wins: 0, Losses: 0, Ties: 0},
	"Broncos":    {Name: "Broncos", Wins: 0, Losses: 0, Ties: 0},
	"Seahawks":   {Name: "Seahawks", Wins: 0, Losses: 0, Ties: 0},
	"Cowboys":    {Name: "Cowboys", Wins: 0, Losses: 0, Ties: 0},
	"Browns":     {Name: "Browns", Wins: 0, Losses: 0, Ties: 0},
	"Commanders": {Name: "Commanders", Wins: 0, Losses: 0, Ties: 0},
	"Buccaneers": {Name: "Buccaneers", Wins: 0, Losses: 0, Ties: 0},
	"Rams":       {Name: "Rams", Wins: 0, Losses: 0, Ties: 0},
	"Lions":      {Name: "Lions", Wins: 0, Losses: 0, Ties: 0},
	"Jets":       {Name: "Jets", Wins: 0, Losses: 0, Ties: 0},
	"49ers":      {Name: "49ers", Wins: 0, Losses: 0, Ties: 0},
}
